brands_models = {
    "Toyota": ["Corolla", "Camry", "RAV4", "Hilux", "Land Cruiser", "Yaris", "Auris", "Supra", "Prius", "Highlander"],
    "Volkswagen": ["Golf", "Passat", "Tiguan", "Polo", "Arteon", "Jetta", "Sharan", "Touran", "Touareg", "ID.4"],
    "Ford": ["Focus", "Mustang", "Fiesta", "Explorer", "F-150", "Mondeo", "Kuga", "Edge", "Ranger", "Escape"],
    "Chevrolet": ["Impala", "Malibu", "Equinox", "Tahoe", "Camaro", "Traverse", "Bolt EV", "Silverado", "Colorado", "Cruze"],
    "Honda": ["Civic", "Accord", "CR-V", "Pilot", "Fit", "Odyssey", "HR-V", "Insight", "Ridgeline", "Element"],
    "BMW": ["3 Series", "5 Series", "7 Series", "X5", "X3", "X1", "M3", "M5", "i3", "i8"],
    "Mercedes-Benz": ["A-Class", "C-Class", "E-Class", "S-Class", "GLA", "GLC", "GLS", "G-Class", "CLA", "EQC"],
    "Audi": ["A3", "A4", "A5", "A6", "A7", "A8", "Q5", "Q7", "Q8", "RS7"],
    "Nissan": ["Altima", "Maxima", "Sentra", "Leaf", "370Z", "Murano", "Rogue", "Pathfinder", "Frontier", "Armada"],
    "Hyundai": ["Elantra", "Sonata", "Tucson", "Santa Fe", "Kona", "Palisade", "Ioniq", "Kona EV", "Veloster", "Nexo"],
    "Kia": ["Optima", "Sorento", "Sportage", "Forte", "Seltos", "Telluride", "Stinger", "Cadenza", "Soul", "Niro"],
    "Tesla": ["Model S", "Model 3", "Model X", "Model Y", "Cybertruck", "Roadster"],
    "Porsche": ["911", "Cayenne", "Macan", "Panamera", "Taycan", "718 Cayman", "Boxster"],
    "Lexus": ["ES", "RX", "NX", "LX", "IS", "GS", "LS", "UX", "RC", "LC"],
    "Subaru": ["Impreza", "Outback", "Forester", "Crosstrek", "Legacy", "BRZ", "Ascent", "WRX"],
    "Mazda": ["Mazda3", "Mazda6", "CX-5", "CX-30", "MX-5 Miata", "CX-9", "Mazda2", "CX-50", "Mazda3 Hatchback"],
    "Peugeot": ["208", "308", "3008", "5008", "Partner", "Traveller", "508", "Rifter", "208 GTi", "Boxer"],
    "Renault": ["Clio", "Captur", "Koleos", "Megane", "Talisman", "Kadjar", "Zoe", "Scenic", "Trafic", "Espace"],
    "Jaguar": ["XE", "XF", "XJ", "F-PACE", "E-PACE", "I-PACE", "F-Type", "XK", "F-Type Coupe"],
    "Land Rover": ["Range Rover", "Discovery", "Evoque", "Defender", "Velar", "Sport", "Freelander", "Discovery Sport"],
    "Ferrari": ["488", "F8 Tributo", "Portofino", "Roma", "GTC4Lusso", "812 Superfast", "LaFerrari", "Dino"],
    "Lamborghini": ["Aventador", "Huracán", "Urus", "Gallardo", "Egoista", "Sián", "Reventón"],
    "Aston Martin": ["DB11", "Vantage", "Rapide", "Vanquish", "DBS Superleggera", "Valhalla", "One-77"],
    "Bentley": ["Continental GT", "Flying Spur", "Bentayga", "Mulsanne", "Brooklands"],
    "Rolls-Royce": ["Phantom", "Ghost", "Wraith", "Dawn", "Cullinan", "Silver Spur"],
    "McLaren": ["720S", "570S", "Artura", "P1", "540C", "650S", "Speedtail"],
    "Bugatti": ["Chiron", "Veyron", "Divo", "Centodieci", "EB110", "Chiron Pur Sport"],
    "Alfa Romeo": ["Giulia", "Stelvio", "Giulia Quadrifoglio", "4C", "Spider", "Giulietta", "Mito", "Tonale"],
    "Fiat": ["Panda", "500", "Tipo", "Punto", "500X", "500L", "Doblo", "Freemont"],
    "Citroën": ["C3", "C4", "C5", "Berlingo", "C3 Aircross", "C5 Aircross", "C6", "SpaceTourer"],
    "Mitsubishi": ["Outlander", "Lancer", "Pajero", "Eclipse Cross", "ASX", "Mirage", "Galant"],
    "Suzuki": ["Swift", "Vitara", "Jimny", "S-Cross", "Baleno", "Ignis", "Celerio", "Liana", "SX4"],
    "Chrysler": ["Pacifica", "Voyager", "300", "Aspen", "Charger", "Durango", "Saratoga"],
    "Dodge": ["Challenger", "Charger", "Durango", "Journey", "Viper", "Grand Caravan", "Ram 1500"],
    "Ram": ["1500", "2500", "3500", "ProMaster", "Promaster City", "Rebel", "TRX"],
    "Buick": ["Enclave", "Encore", "LaCrosse", "Regal", "Verano", "Cascada", "Park Avenue"],
    "GMC": ["Sierra", "Yukon", "Acadia", "Terrain", "Canyon", "Savana", "Canyon AT4", "Sierra HD"],
    "Cadillac": ["Escalade", "XT5", "CT5", "CT6", "CTS", "SRX", "ATS", "Escalade ESV"],
    "Lincoln": ["Nautilus", "Aviator", "Corsair", "Navigator", "MKT", "MKX"],
    "Infiniti": ["Q50", "Q60", "QX50", "QX60", "QX80", "FX50"],
    "Acura": ["MDX", "RDX", "TLX", "ILX", "NSX", "RLX", "ZDX"],
    "Mini": ["Cooper", "Countryman", "Clubman", "Paceman", "John Cooper Works"],
    "Jeep": ["Cherokee", "Grand Cherokee", "Wrangler", "Compass", "Renegade", "Gladiator", "Wagoneer"],
    "Volvo": ["XC90", "XC60", "S60", "S90", "V60", "V90", "XC40", "V40", "C70", "S80"],
    "Skoda": ["Octavia", "Superb", "Fabia", "Kodiaq", "Karoq", "Citigo", "Scala"],
    "Opel": ["Astra", "Corsa", "Insignia", "Mokka", "Grandland X", "Zafira", "Vivaro"],
    "Seat": ["Leon", "Ibiza", "Ateca", "Arona", "Tarraco", "Alhambra"]
}

brands_models = dict(sorted(brands_models.items()))
